language: objective-c
osx_image: xcode7
script:
    - xctool -scheme 'SafeIndex-iOS' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test -parallelize
    - xctool -scheme 'SafeIndex-OSX' test -parallelize
