osx_image: xcode9
language: objective-c
sudo: required
env:
  global:
    - PROJECT="SafeCollection.xcodeproj"
    - SCHEME="SafeCollection-Package"
    - IOS_SDK="iphonesimulator11.0"
    - MACOS_SDK="macosx10.13"
    - TVOS_SDK="appletvsimulator11.0"
    - WATCHOS_SDK="watchsimulator4.0"
    - FRAMEWORK="SafeCollection"
  matrix:
    - SDK="$IOS_SDK"      TEST=1  DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.0"
    - SDK="$MACOS_SDK"    TEST=1  DESTINATION="arch=x86_64"
    - SDK="$TVOS_SDK"     TEST=1  DESTINATION="OS=11.0,name=Apple TV 1080p"
    - SDK="$WATCHOS_SDK"  TEST=0  DESTINATION="OS=4.0,name=Apple Watch - 38mm"

install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - swift --version

before_script:
  - set -o pipefail
  - swift package generate-xcodeproj

script:
  - if [ $TEST == 1 ]; then
      xcodebuild clean build test
        -project "$PROJECT"
        -scheme "$SCHEME"
        -sdk "$SDK"
        -destination "$DESTINATION"
        -configuration Debug
        -enableCodeCoverage YES
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    else
      xcodebuild clean build
        -project "$PROJECT"
        -scheme "$SCHEME"
        -sdk "$SDK"
        -destination "$DESTINATION"
        -configuration Debug
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    fi

after_success:
  - if [ $TEST == 1 ]; then
      bash <(curl -s https://codecov.io/bash) -X xcodeplist -J 'SafeCollection';
    fi
