language: objective-c
osx_image: xcode8
script:
  - xcodebuild -scheme 'SafeIndex' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
  - xcodebuild -scheme 'SafeIndex-OSX' test | xcpretty -c
